name: info_plist_reader
description: A flutter plguin to read info.plist file values
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:  
  plugin:
    platforms:  
      ios:
        pluginClass: InfoPlistReaderPlugin
  